### ISSUE TITLE
not working with rollup +0.45.0

### ISSUE THREAD

**Issue by noeldelgado** [tacoss/tarima#4]
Version: tarima v3.6.1

Rollup 0.45.0 introduced a breaking change.
https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0450

This is part of the output we are getting now when using that version or above:
```sh
Error: bundle.generate(...) now returns a Promise instead of a { code, map } object
    at Promise.get (.../rollup.js:10418:9)
    at Rollup.rollup.then.bundle (.../tarima/lib/support/bundlers/rollup.js:157:27)
```

**Comment by pateketrueke** [comment]
Fixed on `3.7.0` 👍
